"""
Shared PDF report generator for all media types.
Used by the WAHA bot and can replace per-route report logic over time.
"""

import io
import os
import textwrap
from datetime import datetime, timezone

from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter

# Watermark lives next to main.py
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from watermark import add_watermark


def generate_report(result: dict, media_type: str | None = None) -> bytes:
    """
    Generate a branded Niriksha PDF report from any detector result dict.

    Returns the raw PDF bytes (caller decides to save to disk or stream).
    """
    media_type = media_type or result.get("media_type", "unknown")
    verdict = result.get("verdict", "UNKNOWN")
    confidence = result.get("confidence", 0)
    conf_pct = confidence * 100 if confidence <= 1 else confidence

    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)
    w, h = letter

    add_watermark(c, w, h)

    # ── Header ────────────────────────────────────────────────────────
    c.setFont("Helvetica-Bold", 18)
    c.setFillColorRGB(0.2, 0.5, 0.8)
    c.drawString(50, 750, f"NIRIKSHA — {media_type.title()} Forensic Report")
    c.setStrokeColorRGB(0.2, 0.5, 0.8)
    c.line(50, 740, 550, 740)
    c.setFillColorRGB(0, 0, 0)
    y = 710

    # ── Metadata ──────────────────────────────────────────────────────
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    for label, value in [
        ("Generated", now),
        ("Media Type", media_type),
        ("Filename", result.get("filename", "—")),
    ]:
        c.setFont("Helvetica-Bold", 11)
        c.drawString(50, y, f"{label}:")
        c.setFont("Helvetica", 11)
        c.drawString(150, y, str(value))
        y -= 18
    y -= 12

    # ── Verdict ───────────────────────────────────────────────────────
    c.setFont("Helvetica-Bold", 16)
    if verdict == "FAKE":
        c.setFillColorRGB(0.8, 0, 0)
    elif verdict == "REAL":
        c.setFillColorRGB(0, 0.6, 0)
    else:
        c.setFillColorRGB(0.8, 0.6, 0)
    c.drawString(50, y, f"VERDICT: {verdict}")
    c.setFillColorRGB(0, 0, 0)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(250, y, f"Confidence: {conf_pct:.1f}%")
    y -= 35

    # ── Sub-scores ────────────────────────────────────────────────────
    sub_scores = result.get("sub_scores", {})
    if sub_scores:
        c.setFont("Helvetica-Bold", 13)
        c.drawString(50, y, "Analysis Breakdown:")
        y -= 22
        c.setFont("Helvetica", 11)
        for key, val in sub_scores.items():
            label = key.replace("_", " ").title()
            pct = val * 100 if val <= 1 else val
            flag = "  [SUSPICIOUS]" if pct > 50 else ""
            c.drawString(70, y, f"• {label}: {pct:.1f}%{flag}")
            y -= 16
            if y < 60:
                c.showPage()
                add_watermark(c, w, h)
                y = 750
                c.setFont("Helvetica", 11)
        y -= 10

    # ── Explanation ───────────────────────────────────────────────────
    explanation = result.get("explanation", "")
    if explanation:
        c.setFont("Helvetica-Bold", 12)
        c.drawString(50, y, "Summary:")
        y -= 18
        c.setFont("Helvetica", 10)
        for line in textwrap.wrap(explanation, width=85):
            c.drawString(70, y, line)
            y -= 14
            if y < 60:
                c.showPage()
                add_watermark(c, w, h)
                y = 750
                c.setFont("Helvetica", 10)
        y -= 10

    # ── Artifacts ─────────────────────────────────────────────────────
    artifacts = result.get("artifacts_detected", [])
    if artifacts:
        c.setFont("Helvetica-Bold", 12)
        c.drawString(50, y, "Detected Anomalies:")
        y -= 18
        c.setFont("Helvetica", 10)
        for artifact in artifacts:
            for line in textwrap.wrap(f"– {artifact}", width=85):
                if y < 60:
                    c.showPage()
                    add_watermark(c, w, h)
                    y = 750
                    c.setFont("Helvetica", 10)
                c.drawString(70, y, line)
                y -= 14
        y -= 10

    # ── Footer ────────────────────────────────────────────────────────
    if y < 80:
        c.showPage()
        add_watermark(c, w, h)
        y = 750
    c.setStrokeColorRGB(0.8, 0.8, 0.8)
    c.line(50, y + 15, 550, y + 15)
    c.setFont("Helvetica-Oblique", 9)
    c.setFillColorRGB(0.4, 0.4, 0.4)
    c.drawString(50, y, "Generated by Niriksha Forensic Engine — Team 7seas.")
    c.drawString(50, y - 14, "This report is algorithmic and for informational purposes only.")

    c.save()
    buf.seek(0)
    return buf.read()
